"""Add description column to pull list table

Revision ID: 202965ec8d7b
Revises: 943e2d657367
Create Date: 2025-12-01 23:25:52.447452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202965ec8d7b'
down_revision: Union[str, None] = '943e2d657367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_lists', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
