"""Add community rating to comic table

Revision ID: 432387d3f866
Revises: a43fd84cee7b
Create Date: 2025-12-08 11:52:49.446255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432387d3f866'
down_revision: Union[str, None] = 'a43fd84cee7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_column('community_rating')

    # ### end Alembic commands ###
