"""V1 Complete Schema

Revision ID: 7be475332664
Revises: 
Create Date: 2025-12-01 14:33:57.881406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be475332664'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_characters_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_characters_name'), ['name'], unique=True)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_generated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collections_name'), ['name'], unique=True)

    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('scan_on_startup', sa.Boolean(), nullable=True),
    sa.Column('watch_mode', sa.Boolean(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('is_scanning', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_libraries_id'), ['id'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=True)

    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_name'), ['name'], unique=True)

    op.create_table('reading_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_generated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_lists_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_lists_name'), ['name'], unique=True)

    op.create_table('system_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_id'), ['id'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('force_scan', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_jobs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scan_jobs_status'), ['status'], unique=False)

    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_id'), ['id'], unique=False)

    op.create_table('user_libraries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'library_id')
    )
    op.create_table('user_series',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), nullable=True),
    sa.Column('starred_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'series_id')
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volumes_id'), ['id'], unique=False)

    op.create_table('comics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_modified_at', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('day', sa.Integer(), nullable=True),
    sa.Column('web', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('imprint', sa.String(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('series_group', sa.String(), nullable=True),
    sa.Column('scan_information', sa.String(), nullable=True),
    sa.Column('alternate_series', sa.String(), nullable=True),
    sa.Column('alternate_number', sa.String(), nullable=True),
    sa.Column('story_arc', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comics_id'), ['id'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'comic_id', name='unique_collection_comic')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_items_id'), ['id'], unique=False)

    op.create_table('comic_characters',
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comic_id', 'character_id')
    )
    op.create_table('comic_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comic_id', 'person_id', 'role', name='unique_comic_person_role')
    )
    with op.batch_alter_table('comic_credits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comic_credits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comic_credits_role'), ['role'], unique=False)

    op.create_table('comic_locations',
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comic_id', 'location_id')
    )
    op.create_table('comic_teams',
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comic_id', 'team_id')
    )
    op.create_table('reading_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reading_list_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_list_id'], ['reading_lists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reading_list_id', 'comic_id', name='unique_list_comic')
    )
    with op.batch_alter_table('reading_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_list_items_id'), ['id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comic_id', name='unique_user_comic_progress')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_comic_id'), ['comic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_comic_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('reading_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_list_items_id'))

    op.drop_table('reading_list_items')
    op.drop_table('comic_teams')
    op.drop_table('comic_locations')
    with op.batch_alter_table('comic_credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comic_credits_role'))
        batch_op.drop_index(batch_op.f('ix_comic_credits_id'))

    op.drop_table('comic_credits')
    op.drop_table('comic_characters')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_items_id'))

    op.drop_table('collection_items')
    with op.batch_alter_table('comics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comics_id'))

    op.drop_table('comics')
    with op.batch_alter_table('volumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volumes_id'))

    op.drop_table('volumes')
    op.drop_table('user_series')
    op.drop_table('user_libraries')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_id'))

    op.drop_table('series')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_scan_jobs_id'))

    op.drop_table('scan_jobs')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_id'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))
        batch_op.drop_index(batch_op.f('ix_teams_id'))

    op.drop_table('teams')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_category'))

    op.drop_table('system_settings')
    with op.batch_alter_table('reading_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_lists_name'))
        batch_op.drop_index(batch_op.f('ix_reading_lists_id'))

    op.drop_table('reading_lists')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_name'))
        batch_op.drop_index(batch_op.f('ix_people_id'))

    op.drop_table('people')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_name'))
        batch_op.drop_index(batch_op.f('ix_locations_id'))

    op.drop_table('locations')
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_libraries_id'))

    op.drop_table('libraries')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_name'))
        batch_op.drop_index(batch_op.f('ix_collections_id'))

    op.drop_table('collections')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_characters_name'))
        batch_op.drop_index(batch_op.f('ix_characters_id'))

    op.drop_table('characters')
    # ### end Alembic commands ###
