"""Add smart lists table

Revision ID: 8f4012fb169f
Revises: 432387d3f866
Create Date: 2025-12-08 21:48:59.513320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f4012fb169f'
down_revision: Union[str, None] = '432387d3f866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smart_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('query_config', sa.JSON(), nullable=False),
    sa.Column('show_on_dashboard', sa.Boolean(), nullable=True),
    sa.Column('show_in_library', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('smart_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_lists_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_lists_id'))

    op.drop_table('smart_lists')
    # ### end Alembic commands ###
