"""Add pull list tables

Revision ID: 943e2d657367
Revises: 036370b0e945
Create Date: 2025-12-01 19:57:56.346640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943e2d657367'
down_revision: Union[str, None] = '036370b0e945'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pull_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pull_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_lists_id'), ['id'], unique=False)

    op.create_table('pull_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pull_list_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ),
    sa.ForeignKeyConstraint(['pull_list_id'], ['pull_lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_list_id', 'comic_id', name='uq_pull_list_item')
    )
    with op.batch_alter_table('pull_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pull_list_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pull_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_list_items_id'))

    op.drop_table('pull_list_items')
    with op.batch_alter_table('pull_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pull_lists_id'))

    op.drop_table('pull_lists')
    # ### end Alembic commands ###
