"""Add watch mode

Revision ID: a0a283f28ab8
Revises: 034799d1a3af
Create Date: 2025-11-28 19:11:46.277850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a283f28ab8'
down_revision: Union[str, None] = '034799d1a3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('watch_mode', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('libraries', schema=None) as batch_op:
        batch_op.drop_column('watch_mode')

    # ### end Alembic commands ###
