"""add user opds tokens

Revision ID: f3c24a73d963
Revises: 8c2a4f6d9b10
Create Date: 2026-10-03 23:07:01.909986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c24a73d963'
down_revision: Union[str, None] = '8c2a4f6d9b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_opds_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('token_hash', sa.String(), nullable=False),
        sa.Column('token_hint', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('user_opds_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_user_opds_tokens_user_revoked', ['user_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_opds_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_opds_tokens_user_id'), ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_opds_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_opds_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_opds_tokens_id'))
        batch_op.drop_index('idx_user_opds_tokens_user_revoked')

    op.drop_table('user_opds_tokens')
    # ### end Alembic commands ###
